### ISSUE TITLE
老铁，运行npm run dev的时候出错了

### ISSUE THREAD

**Issue by Stephen-Z** [boylegu/SpringBoot-vue#45]
➜  frontend git:(master) ✗ npm run dev

> webpack2@1.0.0 dev /Users/stephen/Documents/workspace/spring_vue/SpringBoot-vue/frontend
> node build/dev.js

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1315:14)
    at listenInCluster (net.js:1363:12)
    at doListen (net.js:1489:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack2@1.0.0 dev: `node build/dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack2@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by boylegu** [comment]
找到原因了么？看上去像是端口被占用了

**Comment by Stephen-Z** [comment]
找到了，是端口问题。
________________________________
发件人: Boyle Gu <notifications@github.com>
发送时间: 2017年7月17日 11:15:22
收件人: boylegu/SpringBoot-vue
抄送: StephenZhang; State change
主题: Re: [boylegu/SpringBoot-vue] 老铁，运行npm run dev的时候出错了 (#45)


找到原因了么？看上去像是端口被占用了

―
