### ISSUE TITLE
启动后，访问http://localhost:8000//api/persons报错

### ISSUE THREAD

**Issue by stephenwang2017** [boylegu/SpringBoot-vue#46]
2017-07-20 15:23:28.396  WARN 6165 --- [nio-8000-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved exception caused by Handler execution: org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'sex' is not present
2017-07-20 15:23:28.510 ERROR 6165 --- [nio-8000-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'timestamp' cannot be found on object of type 'java.util.HashMap' - maybe not public?] with root cause

org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'timestamp' cannot be found on object of type 'java.util.HashMap' - maybe not public?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:224) ~[spring-expression-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94) ~[spring-expression-4.3.8.RELEASE.jar:4.3.8.RELEASE]

**Comment by boylegu** [comment]
不好意思，给你造成了困扰和不便深表歉意，你提的issue确实是个Bug，API设计的并不是很周到，目前必须要加上sex和email这两个QueryString，如：http://localhost:8000/api/persons?sex=&email=
这个问题之后会进行修复，让API更灵活一些，非常感谢！
